# General settings
base_settings:
  n_games: 100

# Agent settings
agent:
  alpha: 0.0005
  beta: 0.0003
  gamma: 0.99
  tau: 0.005
  max_size: 1_000_000
  layer1_size: 256
  layer2_size: 256
  batch_size: 256
  reward_scale: 2

# Network settings
actor:
  log_mu_max: 2
  log_mu_min: -5