# General settings
base_settings:
  n_games: 250

# Agent settings
hp:
  alpha_min: 0.0005
  alpha_max: 0.0005

  beta_min: 0.0003
  beta_max: 0.0003

  gamma_min: 0.99
  gamma_max: 0.99

  layer_count_min: 2
  layer_count_max: 4

  layer_size_min: 32
  layer_size_max: 256

  tau: 0.005
  max_size: 1_000_000
  batch_size: 256
  reward_scale: 2