# General settings
base_settings:
  n_games: 40
  render_skip_size: 50
  avg_lookback: 50
  dt: 0.1
  t_max: 2500

# Agent settings
agent:
  alpha: 0.0005
  beta: 0.0003
  gamma: 0.99
  tau: 0.005
  max_size: 1_000_000
  layer1_size: 256
  layer2_size: 256
  batch_size: 256
  reward_scale: 2

# Env settings
boat_env:
  track_width: 500
  boat_out_of_bounds_offset: 0
  wind_force: 1 # How many degrees per step the wind turns the ship
  goal_line: 3900

# Boat modelling settings
boat:
  n_max: 20
  fuel: 6000 # Also t_max

  w: 0.3
  boat_m: 600
  boat_m_x: 50
  boat_m_y: 100

  boat_I: 6_000_000
  boat_Iz: 10

  propeller_diameter: 1
  wake_friction: 0.3

  c_r_front: 0.31
  c_r_side: 2
  thrust_deduction: 0.3

  rho: 1

  boat_area_front: 20
  boat_area_side: 90
  boat_l: 15
  boat_b: 6

  rudder_area: 10
  aspect_ratio: 2
  a: 4.252
  b: 0.262

# Wind settings
wind:
  range_length: 10000
  fixed_points: 4
  max_force: 1

# Permanent settings for testing
test:
  track_width: 5
  nested_test: 5
  boat_velocity: 1
  boat_angle_scale: 1
  wind_events: 3
  wind_force: 5
